---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lotrackg/public_html/
    - /bin/cp -R contact $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R email $DEPLOYPATH
    - /bin/cp -R font-awesome $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R img-fb $DEPLOYPATH
    - /bin/cp -R inc $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R phpmailer $DEPLOYPATH
    - /bin/cp -R portfolio-grafica $DEPLOYPATH
    - /bin/cp -R portfolio-siti $DEPLOYPATH
    - /bin/cp -R svg $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp *.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
